[package]
name = "rustscii"
version = "0.1.0"
description = "A Rust ASCII game framework."
authors = ["josé luiz <jlc.beker@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
gfx = "0.18.3"
winit = "0.28.6"
image = "0.24.7"